# -*- coding: utf-8 -*-
"""AULA3-NEY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L23uU6PPyGL7O9WN6HYdubAoOIfpOQv-
"""

import pandas as pd

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]

series = pd.Series(lista)

print(series)
print("aaaaa")
print(lista)

import pandas as pd

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]

series = pd.Series(lista, index=["zero", "um", "dois", "tres", "quatro", "cinco", "seis", "sete", "oito"])

print(series)

import pandas as pd

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]

series = pd.Series(lista, index=["zero", "um", "dois", "tres", "quatro", "cinco", "seis", "sete", "oito"])

print(series.index)

import pandas as pd

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]

series = pd.Series(lista, index=["zero", "um", "dois", "tres", "quatro", "cinco", "seis", "sete", "oito"])

series[series>4]

import pandas as pd

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]

series = pd.Series(lista, index=["zero", "um", "dois", "tres", "quatro", "cinco", "seis", "sete", "oito"])

series*10

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

# Create a DataFrame from the dataset
dataframe_sc = pd.DataFrame(dataset)

# Display the DataFrame
display(dataframe_sc)

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# ver primeiras linhas
print(dataframe_sc.head(3))

print('-----')

# ver ultimas linhas
print(dataframe_sc.tail(3))

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# ver primeiras linhas
print(dataframe_sc['Populacao'])

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# mudar posicao
dataframe_sc2 = pd.DataFrame(dataset, columns=['Populacao', 'IDH', 'Ano de Emancipacao', 'Cidades'])

# adicionar nova coluna
dataframe_sc2['Regiao'] = 'Sul'

print(dataframe_sc2)

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# mudar posicao
dataframe_sc2 = pd.DataFrame(dataset, columns=['Populacao', 'IDH', 'Ano de Emancipacao', 'Cidades'])

# adicionar nova coluna CONDICIONAL
dataframe_sc2['Grande'] = dataframe_sc2['Populacao'] >= 300000

print(dataframe_sc2)

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# mudar posicao
dataframe_sc2 = pd.DataFrame(dataset, columns=['Populacao', 'IDH', 'Ano de Emancipacao', 'Cidades'])

# adicionar nova coluna
dataframe_sc2['Regiao'] = 'Sul'

print(dataframe_sc2)
print('--------------------------------------------')

# EXCLUIR COLUNA
dataframe_sc2.drop('Regiao', axis=1, inplace=True)

print(dataframe_sc2)

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# mudar posicao
dataframe_sc2 = pd.DataFrame(dataset, columns=['Populacao', 'IDH', 'Ano de Emancipacao', 'Cidades'])

# adicionar nova coluna
dataframe_sc2['Regiao'] = 'Sul'

print(dataframe_sc2)
print('--------------------------------------------')

# EXCLUIR LINHA
dataframe_sc2.drop(1, axis=0, inplace=True)

print(dataframe_sc2)

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# mudar posicao
dataframe_sc2 = pd.DataFrame(dataset, columns=['Populacao', 'IDH', 'Ano de Emancipacao', 'Cidades'])

# adicionar nova coluna
dataframe_sc2['Regiao'] = 'Sul'

print(dataframe_sc2)
print('--------------------------------------------')

# MUDAR OS NOMES
dataframe_sc2.rename(columns={'Cidades': 'Cidade'}, inplace=True)
dataframe_sc2.rename(columns={'Ano de Emancipacao': 'Emancipacao'}, inplace=True)

print(dataframe_sc2)

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# TIPOS DE DADOS
dataframe_sc.dtypes

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# CONTAR QUANTOS ELEMENTOS EM CADA CATEGORIA (BOM PARA VER SE TEM COISA FLATANDO)
dataframe_sc.count()

import pandas as pd

dataset = {
    'Cidades': ['Florianópolis', 'Joinville', 'Criciúma', 'Lages', 'Brusque'],
    'Populacao': [508826, 604700, 215987, 157749, 134808], # Added approximate population data
    'IDH': [0.847, 0.794, 0.785, 0.777, 0.775], # Added approximate IDH data
    'Ano de Emancipacao': [1726, 1851, 1925, 1766, 1860] # Added approximate emancipation year
}

dataframe_sc = pd.DataFrame(dataset)

# ANALISE DESCRITIVA DE DADOS METODO DESCRIBE
dataframe_sc.describe()